# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b746ba0d327b7777b35b357735bd4595df2bf3237a8dc816b7a1c03e309d4cbfd27b5723b10d686160ff8cf7d307ed3e7a7178716165e8f67b9c0657c35f732

test:
  secret_key_base: 1264c06909d66453b45418afecae6318808d65a91a88ab3969725809cf911234bbe884f8d593c7a9747df0c2a152687fa0fe1a07dd2adb10a140c7ece4abccba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
